[projects."kommunekredit@vs-ssh.visualstudio.com:v3/kommunekredit/KK%20Laaneportal/KommuneKredit.Frontend"]
approved-commands = [
    "pnpm install --frozen-lockfile --reporter=silent",
    "pnpm install --prefer-offline --frozen-lockfile --reporter=silent",
]
