worktree-path = "../{{ branch }}"

[pre-switch]
pull-latest = "$HOME/.config/worktrunk/hooks/pull-latest.sh"

[post-create]
recent-worktree = "printf '%s\n' {{ worktree_path }} >> /tmp/.recent-worktrees"
