worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[pre-switch]
pull-latest = "$HOME/.config/worktrunk/hooks/pull-latest.sh"

[pre-start]
copy-ignored = "wt step copy-ignored"
recent-worktree = "printf '%s\n' {{ worktree_path }} >> /tmp/.recent-worktrees"
