import app from "ags/gtk4/app";
import "@/components/ai-pointer/install-host-runtime";
import "./styles.case";
import "./confirm-dialog.case";
import "./start-menu.case";
import "./audio-mixer.case";
import "./calendar.case";
import "./keyboard-switcher.case";
import "./volume-indicator.case";
import "./force-quit.case";
import "./about-this-pc.case";
import "./ai-pointer.case";
import "./ai-pointer-workflow-boundaries.case";
import "./ai-pointer-workflow-selection.case";
import "./ai-pointer-process-lifecycle.case";
import "./ai-pointer-view.case";
import "./ai-pointer-workflow.case";
import "./window-switcher.case";
import "./window-switcher-preview-cache.case";
import { runSuite } from "./harness";

app.register(null);
await runSuite();
