# CPU-focused popup preset (for Waybar click)

color_theme = "zenwritten-dark"
theme_background = true
truecolor = true

presets = "cpu:1:default,proc:0:default mem:1:default,proc:0:default"
shown_boxes = "cpu proc"

proc_sorting = "cpu lazy"
proc_reversed = false
proc_tree = false

check_temp = true
show_coretemp = true
update_ms = 1000
