-- Auto-generated Lua window rules by hypr-quickrule
--
return {
	-- BEGIN quickrule:class:yad:floating-medium
	{
		id = "quickrule:class:yad:floating-medium",
		match = {
			class = "^(yad)$",
		},
		effects = {
			float = true,
			size = { 750, 900 },
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for yad",
	},
	-- END quickrule:class:yad:floating-medium

	-- BEGIN quickrule:class:GParted:floating-small
	{
		id = "quickrule:class:GParted:floating-small",
		match = {
			class = "^(GParted)$",
		},
		effects = {
			float = true,
			size = { 360, 620 },
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for GParted",
	},
	-- END quickrule:class:GParted:floating-small

	-- BEGIN quickrule:class:be\.alexandervanhee\.gradia:floating-centered
	{
		id = "quickrule:class:be\\.alexandervanhee\\.gradia:floating-centered",
		match = {
			class = "^(be\\.alexandervanhee\\.gradia)$",
		},
		effects = {
			float = true,
			center = true,
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for be.alexandervanhee.gradia",
	},
	-- END quickrule:class:be\.alexandervanhee\.gradia:floating-centered

	-- BEGIN quickrule:class:net\.davidotek\.pupgui2:floating-medium
	{
		id = "quickrule:class:net\\.davidotek\\.pupgui2:floating-medium",
		match = {
			class = "^(net\\.davidotek\\.pupgui2)$",
		},
		effects = {
			float = true,
			size = { 750, 900 },
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for net.davidotek.pupgui2",
	},
	-- END quickrule:class:net\.davidotek\.pupgui2:floating-medium

	-- BEGIN quickrule:class:net\.davidotek\.pupgui2:floating-small
	{
		id = "quickrule:class:net\\.davidotek\\.pupgui2:floating-small",
		match = {
			class = "^(net\\.davidotek\\.pupgui2)$",
		},
		effects = {
			float = true,
			size = { 360, 620 },
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for net.davidotek.pupgui2",
	},
	-- END quickrule:class:net\.davidotek\.pupgui2:floating-small

	-- BEGIN quickrule:migrated:proton-vpn:float
	{
		id = "quickrule:migrated:proton-vpn:float",
		match = {
			initial_class = "^(proton\\.vpn\\.app\\.gtk)$",
			initial_title = "^(Proton VPN)$",
		},
		effects = {
			float = true,
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for proton.vpn.app.gtk - Proton VPN",
	},
	-- END quickrule:migrated:proton-vpn:float

	-- BEGIN quickrule:migrated:steam-app-0-spaceship-escape:floating-centered
	{
		id = "quickrule:migrated:steam-app-0-spaceship-escape:floating-centered",
		match = {
			initial_class = "^(steam_app_0)$",
			initial_title = "^(spaceship_escape)$",
		},
		effects = {
			float = true,
			center = true,
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for steam_app_0 - spaceship_escape",
	},
	-- END quickrule:migrated:steam-app-0-spaceship-escape:floating-centered

	-- BEGIN quickrule:class:io\.github\.efogdev\.mpris-timer:floating-small
	{
		id = "quickrule:class:io\\.github\\.efogdev\\.mpris-timer:floating-small",
		match = {
			class = "^(io\\.github\\.efogdev\\.mpris-timer)$",
		},
		effects = {
			float = true,
			size = { 360, 620 },
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for io.github.efogdev.mpris-timer",
	},
	-- END quickrule:class:io\.github\.efogdev\.mpris-timer:floating-small

	-- BEGIN quickrule:class:io\.github\.efogdev\.mpris-timer:floating-pinned
	{
		id = "quickrule:class:io\\.github\\.efogdev\\.mpris-timer:floating-pinned",
		match = {
			class = "^(io\\.github\\.efogdev\\.mpris-timer)$",
		},
		effects = {
			float = true,
			pin = true,
		},
		source = "quickrule",
		comment = "Generated by hypr-quickrule for io.github.efogdev.mpris-timer",
	},
	-- END quickrule:class:io\.github\.efogdev\.mpris-timer:floating-pinned
}
