return function()
  vim.cmd("colorscheme zenwritten")
  vim.highlight.create("TreesitterContext", { guibg = "#2c2c2c" })
  -- popup menu hihlights (wilder, telescope, etc.)
  vim.highlight.create("NormalFloat", { guibg = "#191919" })
  vim.highlight.create("Pmenu", { guibg = "#191919" })
  vim.highlight.create("Beacon", { guibg = "#bbbbbb", ctermbg = 15 })
  -- cmp highlighs
  vim.highlight.create("CmpItemAbbrDeprecated", { guibg=0, guifg="#bbbbbb", gui="strikethrough"})
  vim.highlight.create("CmpItemAbbrMatch", { guibg=0, guifg="#aaaaaa" })
  vim.highlight.create("CmpItemAbbrMatchFuzzy", { guibg=0, guifg="#aaaaaa" })
  vim.highlight.create("CmpItemKindVariable", { guibg=0, guifg="#97bdde" })
  vim.highlight.create("CmpItemKindInterface", { guibg=0, guifg="#97bdde" })
  vim.highlight.create("CmpItemKindText", { guibg=0, guifg="#97bdde" })
  vim.highlight.create("CmpItemKindFunction", { guibg=0, guifg="#b279a7" })
  vim.highlight.create("CmpItemKindMethod", { guibg=0, guifg="#b279a7" })
  vim.highlight.create("CmpItemKindKeyword", { guibg=0, guifg="#bbbbbb" })
  vim.highlight.create("CmpItemKindProperty", { guibg=0, guifg="#ffffff" })
  vim.highlight.create("CmpItemKindUnit", { guibg=0, guifg="#ffffff" })
end
