return function()
  require("nvim-tree").setup({})
  local tree_events = require("nvim-tree.events")
  local bufferline_state = require("bufferline.state")
  tree_events.on_tree_open(function()
       bufferline_state.set_offset(31, "FileTree")
  end)
  tree_events.on_tree_close(function()
      bufferline_state.set_offset(0)
  end)
end
