# Minimal foot config matching wezterm aesthetic

[main]
font = Zenbones Brainy:size=11.8:weight=light, Symbols Nerd Font Mono:size=8.8, BabelStone Runic Elder Futhark:size=10.8, Apple Color Emoji:size=11.8
dpi-aware = yes
workers = 6
pad = 2x0

[bell]
urgent = no
notify = no
visual = no

[cursor]
style = block
blink = no

# zenwritten_dark colors
[colors-dark]
alpha = 1.0
foreground = b7b7b7
background = 191919
selection-foreground = bbbbbb
selection-background = 404040
cursor = 191919 c9c9c9

# Normal colors
regular0 = 191919
regular1 = e388a3
regular2 = 98bd99
regular3 = b77e64
regular4 = 7facca
regular5 = b279a7
regular6 = 7facca
regular7 = bbbbbb

# Bright colors
bright0 = 3d3839
bright1 = eb99b1
bright2 = 8fcd92
bright3 = d68c67
bright4 = 97bdde
bright5 = cf86c1
bright6 = 97bdde
bright7 = 8e8e8e

[csd]
preferred = none
size = 12
border-width = 0

[tweak]
grapheme-shaping = no
