require("plugins.adaptive_soft_shadow")
require("plugins.custom_layout_resize")
require("plugins.cursor_outline")
require("plugins.focus_animation")
require("plugins.inset_border")
require("plugins.pointer_edge_hooks")
