# See https://wiki.hypr.land/Configuring/Environment-variables/

env = XDG_CURRENT_DESKTOP,Hyprland
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HOVER_Y_THRESHOLD,auto
env = HOVER_Y_MARGIN,12
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_GSYNC_ALLOWED,1
env = LIBVA_DRIVER_NAME,nvidia

# NVIDIA-specific settings to fix cursor flickering
