-- Static layer rules ported from appearance.conf.
-- Preserve declaration order.

hl.layer_rule({ match = { namespace = "waybar" }, blur = true })
hl.layer_rule({ match = { namespace = "vicinae" }, blur = true })
hl.layer_rule({ match = { namespace = "rofi" }, blur = true })
hl.layer_rule({ match = { namespace = "nemo" }, blur = true })
hl.layer_rule({ match = { namespace = "vicinae" }, no_anim = true })
hl.layer_rule({ match = { namespace = "rofi" }, ignore_alpha = 0 })
hl.layer_rule({ match = { namespace = "swaync-control-center" }, blur = true })
hl.layer_rule({ match = { namespace = "swaync-control-center" }, no_anim = true })
hl.layer_rule({ match = { namespace = "swaync-notification-window" }, blur = true })
hl.layer_rule({ match = { namespace = "swaync-notification-window" }, no_anim = true })
hl.layer_rule({ match = { namespace = "swayosd" }, blur = true })
hl.layer_rule({ match = { namespace = "ags-confirm" }, blur = true })
hl.layer_rule({ match = { namespace = "ags-confirm" }, animation = "popin 90%" })
hl.layer_rule({ match = { namespace = "ags-layout-switcher" }, blur = true })
hl.layer_rule({ match = { namespace = "ags-layout-switcher" }, no_anim = true })
hl.layer_rule({ match = { namespace = "ags-volume-indicator" }, blur = true })
hl.layer_rule({ match = { namespace = "ags-volume-indicator" }, no_anim = true })
hl.layer_rule({ match = { namespace = "ags-window-switcher" }, blur = true })
hl.layer_rule({ match = { namespace = "ags-window-switcher" }, no_anim = true })
hl.layer_rule({ match = { namespace = "vicinae" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "waybar" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "swaync-control-center" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "swaync-notification-window" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "swayosd" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "ags-confirm" }, ignore_alpha = 0.5 })
hl.layer_rule({ match = { namespace = "ags-layout-switcher" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "ags-volume-indicator" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "ags-window-switcher" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "ags-start-menu" }, blur = true })
hl.layer_rule({ match = { namespace = "ags-start-menu" }, no_anim = true })
hl.layer_rule({ match = { namespace = "ags-start-menu" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "ags-desktop-clock" }, blur = true })
hl.layer_rule({ match = { namespace = "ags-desktop-clock" }, ignore_alpha = 0.3 })
hl.layer_rule({ match = { namespace = "ags-desktop-clock" }, no_anim = true })
