require("config.builtins")
require("config.opts")
require("config.direnv").setup()
require("config.usercmd")
require("config.keymaps")
require("config.autocmd")
require("config.abbr")
require("config.pack")
