const acronymsArray = [
	"api",
	"aws",
	"css",
	"cpu",
	"db",
	"dev",
	"doc",
	"gpu",
	"html",
	"id",
	"ip",
	"js",
	"nfc",
	"npm",
	"pdf",
	"sql",
	"ui",
	"url",
	"usb",
	"vm",
	"vpn",
	"xml",
];

export const ACRONYMS = new Set(acronymsArray);

export const TOKEN_SYNONYMS: Record<string, string[]> = {
	account: ["user", "profile", "person", "avatar"],
	add: ["plus", "new"],
	alert: ["warning", "caution", "triangle"],
	anchor: ["ship", "boat"],
	app: ["application", "program"],
	arrow: ["direction", "chevron", "pointer"],
	audio: ["sound", "speaker", "volume"],
	back: ["previous", "left"],
	bell: ["notification", "alert"],
	bird: ["animal"],
	bolt: ["lightning", "electric", "flash"],
	book: ["read", "library", "manual"],
	box: ["container", "package"],
	bug: ["issue", "defect", "problem"],
	bulb: ["idea", "light"],
	camera: ["photo", "picture"],
	cancel: ["close", "stop", "abort"],
	car: ["vehicle", "auto"],
	cart: ["shopping", "basket"],
	certificate: ["badge", "award"],
	chat: ["message", "speech", "bubble"],
	check: ["tick", "confirm", "done", "ok", "success"],
	circle: ["round", "button"],
	clipboard: ["copy", "paste"],
	close: ["cross", "cancel", "x"],
	cloud: ["upload", "download", "storage"],
	code: ["developer", "program"],
	cog: ["settings", "gear", "preferences"],
	column: ["layout"],
	comment: ["message", "chat"],
	compass: ["navigation", "direction"],
	copy: ["duplicate", "clone"],
	cpu: ["processor", "chip"],
	cross: ["close", "cancel", "multiply"],
	delete: ["remove", "trash", "bin"],
	desktop: ["computer", "monitor"],
	document: ["file", "paper"],
	download: ["save", "arrow down"],
	edit: ["pencil", "write"],
	email: ["mail", "envelope"],
	error: ["issue", "problem", "warning"],
	exit: ["logout", "leave"],
	file: ["document", "paper"],
	filter: ["funnel", "narrow"],
	flag: ["marker", "milestone"],
	folder: ["directory"],
	forward: ["next", "right"],
	gift: ["present"],
	globe: ["world", "earth"],
	graph: ["chart"],
	grid: ["layout"],
	heart: ["like", "love", "favorite"],
	help: ["question", "support"],
	home: ["house"],
	image: ["picture", "photo"],
	info: ["information", "details"],
	light: ["sun", "bright"],
	link: ["chain", "url"],
	list: ["menu", "items", "bullet"],
	lock: ["secure", "security"],
	login: ["sign in"],
	logout: ["sign out", "exit"],
	magnifier: ["search", "find"],
	menu: ["hamburger", "navigation"],
	message: ["chat", "speech"],
	microphone: ["audio", "voice", "record"],
	minus: ["remove", "dash"],
	moon: ["night", "dark"],
	music: ["audio", "note", "song"],
	mute: ["silent", "speaker"],
	notification: ["alert", "bell"],
	open: ["unlock"],
	palette: ["color", "paint"],
	paperclip: ["attachment"],
	pause: ["stop"],
	pay: ["money", "currency"],
	pen: ["edit", "write", "pencil"],
	pencil: ["edit", "draw", "write"],
	people: ["users", "group", "team"],
	phone: ["call", "telephone"],
	picture: ["photo", "image"],
	play: ["start", "triangle"],
	plug: ["power", "electric"],
	plus: ["add", "new"],
	power: ["shutdown", "off"],
	print: ["printer"],
	question: ["help", "support"],
	redo: ["forward", "arrow"],
	refresh: ["reload", "sync", "update"],
	remove: ["delete", "trash"],
	repeat: ["loop"],
	reply: ["answer"],
	rocket: ["ship", "launch"],
	save: ["disk"],
	search: ["find", "magnifying", "magnifier"],
	settings: ["cog", "gear", "preferences"],
	share: ["export", "send"],
	shield: ["security", "protection"],
	skip: ["jump"],
	sort: ["order"],
	speaker: ["audio", "sound", "volume"],
	star: ["favorite", "bookmark", "rating"],
	status: ["indicator"],
	stop: ["square", "halt"],
	sun: ["day", "light"],
	sync: ["refresh", "reload", "update"],
	tag: ["label", "badge"],
	target: ["aim", "bullseye"],
	terminal: ["cli", "command", "prompt"],
	text: ["font", "type"],
	time: ["clock", "schedule"],
	timer: ["clock", "alarm"],
	toggle: ["switch"],
	trash: ["delete", "remove", "bin"],
	unlock: ["access", "open"],
	update: ["refresh", "sync"],
	upload: ["arrow up"],
	user: ["person", "account", "profile"],
	video: ["movie", "camera"],
	volume: ["speaker", "sound", "audio"],
	warning: ["alert", "triangle"],
	wifi: ["network", "signal"],
	window: ["app", "application"],
	write: ["edit", "pencil"],
	x: ["close", "cancel", "cross"],
	dog: ["puppy", "animal", "pet"],
	cat: ["kitten", "animal", "pet"],
	left: ["previous", "west", "back"],
	right: ["next", "east", "forward"],
	up: ["north", "increase", "raise"],
	down: ["south", "decrease", "lower"],
	times: ["close", "cross", "multiply"],
	lightning: ["bolt", "electric"],
};

export function addSynonyms(token: string): string[] {
	const synonyms = TOKEN_SYNONYMS[token] ?? [];
	const extras: string[] = [];

	if (token === "plus") {
		extras.push("+", "add");
	}
	if (token === "minus") {
		extras.push("-", "subtract");
	}
	if (token === "times") {
		extras.push("x");
	}
	if (token === "close") {
		extras.push("quit");
	}

	return [...synonyms, ...extras].map((entry) => entry.toLowerCase());
}
