name: Smoke Test

on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./scripts

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: ./brew-install-script.sh
